### ISSUE TITLE
 Error while running make

### ISSUE THREAD

**Issue by Cinder4198** [xerpi/vita-baremetal-loader#3]
I was following the guide for the ps vita linux build, and when trying to build vita baremetal loader, it came up with this error put below

After looking it up, it seemed to suggest it could be something within the C code, but I'm not too sure.
Running Linux Mint 21.2 Cinnamon, Cinnamon Version 5.8.4, Linux Kernal 5.15.0-89-generic.

> arm-vita-eabi-gcc    -c -o resume.o resume.S
arm-vita-eabi-gcc    -c -o payload_bootstrap.o payload_bootstrap.S
arm-vita-eabi-gcc -T payload_bootstrap.ld -nostartfiles -nostdlib payload_bootstrap.o -o payload_bootstrap.elf -lgcc
arm-vita-eabi-objcopy -S -O binary payload_bootstrap.elf payload_bootstrap.bin
arm-vita-eabi-objcopy -I binary -O elf32-littlearm --binary-architecture arm payload_bootstrap.bin payload_bootstrap_bin.o
arm-vita-eabi-gcc -Wl,-q -Wall -O0 -nostartfiles -mcpu=cortex-a9 -mthumb-interwork main.o resume.o payload_bootstrap_bin.o -ltaihenForKernel_stub -lSceSysclibForDriver_stub -lSceSysmemForDriver_stub -lSceThreadmgrForDriver_stub -lSceCpuForDriver_stub -lScePervasiveForDriver_stub -lSceSysconForDriver_stub -lScePowerForDriver_stub -lSceIofilemgrForDriver_stub -lSceSysrootForKernel_stub -lSceSysmemForKernel_stub -lSceCpuForKernel_stub -lSceUartForKernel_stub -o baremetal-loader.elf
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: main.o: in function `setup_payload':
main.c:(.text+0x12c): undefined reference to `ksceKernelCpuDcacheAndL2WritebackRange'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: main.o: in function `ksceSysconResetDevice_hook_func':
main.c:(.text+0x1fa): undefined reference to `ksceKernelCpuDcacheWritebackInvalidateAll'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: main.c:(.text+0x1fe): undefined reference to `ksceKernelCpuIcacheInvalidateAll'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: main.o: in function `module_start':
main.c:(.text+0x59a): undefined reference to `ksceKernelCpuUnrestrictedMemcpy'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: main.o: in function `load_file_phycont':
main.c:(.text+0xa10): undefined reference to `ksceKernelCpuDcacheAndL2WritebackRange'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: main.c:(.text+0xa1a): undefined reference to `ksceKernelCpuIcacheInvalidateRange'
collect2: error: ld returned 1 exit status
make: *** [Makefile:38: baremetal-loader.elf] Error 1

**Comment by xerpi** [comment]
After updating VITASDK I'm getting the same error. I'll fix it now.
